services:
  proxy-kernel:
    image: metacubex/mihomo
    restart: always
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
      # - ./ui:/ui:ro # 仪表盘 Volume 映射
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    network_mode: "host"